apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Values.namespace | lower | quote}}
  name: {{(print .Values.service "-deployment")| lower | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.service | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
{{- if ( default false .Values.useCanary ) }}
  # ref: https://argoproj.github.io/argo-rollouts/migrating/
  replicas: 0   # Scale down existing deployment
{{- else }}
  replicas: {{ .Values.replicaCount.default }}
{{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{.Values.service | lower | quote}}
      version: {{ .Values.version | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.service | lower | quote }}
        app.kubernetes.io/part-of: {{ .Values.system | quote }}
        app.kubernetes.io/version: {{ .Values.version | quote }}
        app: {{.Values.service | lower | quote}}
        version: {{ .Values.version | quote }}
    spec:
      containers:
        - name: {{.Values.service | lower | quote}}
          image: {{printf "%s:%s" .Values.image.repository .Values.image.tag}}
          imagePullPolicy: {{ .Values.image.imagePullPolicy | quote }}
          ports:
            - containerPort: {{.Values.image.containerPort}}
          env:
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
{{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
{{- if .Values.probes }}
{{ toYaml .Values.probes | indent 10 }}
{{- end }}