{{- if .Values.autoscaling }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: {{ .Values.service | lower | quote }}
    labels:
        app.kubernetes.io/name: {{ .Values.service | lower | quote }}
        app.kubernetes.io/part-of: {{ .Values.system | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    namespace: {{.Values.namespace | lower | quote}}
spec:
    scaleTargetRef:
{{- if ( default false .Values.useCanary ) }}
        apiVersion: argoproj.io/v1alpha1
        kind: Rollout
        name: {{ .Values.service | lower | quote }}
{{- else }}
        apiVersion: apps/v1
        kind: Deployment 
        name: {{(print .Values.service "-deployment")| lower | quote }}
{{- end }}
    minReplicas: {{ .Values.autoscaling.minReplicas }}
    maxReplicas: {{ .Values.autoscaling.maxReplicas }}
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: {{ .Values.autoscaling.targetAverageCpuUtilization }}
{{- end }}