apiVersion: v1
kind: Service
metadata:
  name:  {{(print .Values.service "-ingressgateway") | lower }}
  namespace: istio-ingress
  labels:
    app.kubernetes.io/name: {{ .Values.service | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app:  {{(print .Values.service "-ingressgateway") | lower }}
spec:
  type: NodePort
  selector:
    istio: {{(print .Values.service "-ingressgateway") | lower }}
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: {{.Values.servicePort}}
    nodePort: {{.Values.nodePort}}