apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace | lower | quote}}
  labels:
    istio-injection: enabled
    app.kubernetes.io/name: {{(print .Values.service "-namespace") | lower }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}