apiVersion: v1
kind: Service
metadata:
  name: {{(print .Values.service "-service") | lower | quote }}
  namespace:  {{.Values.namespace | lower | quote}}
  labels:
    app.kubernetes.io/name: {{ .Values.service | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    version: {{ .Values.version | quote }}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.service | lower | quote}}
  ports:
    - port: {{.Values.servicePort}}
      protocol: TCP
      targetPort: {{.Values.image.containerPort}}