apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{(print .Values.service "-virtualService") | lower | quote }}
  namespace: {{.Values.namespace | lower | quote}}
  labels:
    app.kubernetes.io/name: {{ .Values.service | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  hosts:
  - {{.Values.domainName | quote}}
  gateways:
  - {{(print .Values.service "-gateway") | lower }}
  http:
  - match:
    route:
{{- if ( default false .Values.useCanary ) }}
    - destination:
        subset: stable
        host: {{(printf "%s-service.%s.svc.cluster.local" .Values.service .Values.namespace) | lower}}
        port:
          number: {{.Values.servicePort}}
      weight: 100
    - destination:
        subset: canary
        host: {{(printf "%s-service.%s.svc.cluster.local" .Values.service .Values.namespace) | lower}}
        port:
          number: {{.Values.servicePort}}
      weight: 0 
{{- else }}
      - destination:
          host: {{(printf "%s-service.%s.svc.cluster.local" .Values.service .Values.namespace) | lower}}
          subset: {{ (print "v" .Values.version) | quote }}
          port:
            number: {{.Values.servicePort}}
{{- end }}